ALTER TABLE `PlayerReviews`
CHANGE `ReviewId` `ParentId` INT(10) UNSIGNED NULL,
ADD COLUMN `ToPlayerId` INT UNSIGNED NULL AFTER `ParentId`,
CHANGE `IsPromo` `IsPromo` TINYINT(1) UNSIGNED DEFAULT 0 NOT NULL,
CHANGE `UserId` `AdminId` INT(11) UNSIGNED DEFAULT 0 NOT NULL AFTER `Status`,
ADD COLUMN `Module` ENUM('comments','blog') DEFAULT 'comments' NOT NULL AFTER `AdminId`,
ADD COLUMN `ObjectId` INT UNSIGNED DEFAULT 0 NOT NULL AFTER `Module`,
ADD COLUMN `ModifyDate` INT(11) NOT NULL AFTER `ObjectId`;
