ALTER TABLE `ShopOrders` CHANGE `UserId` `AdminId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `MoneyOrders` CHANGE `UserId` `AdminId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `PlayerNotes` CHANGE `UserId` `AdminId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `PlayerNotices` CHANGE `UserId` `AdminId` INT(11) UNSIGNED NOT NULL DEFAULT '0';
