CREATE TABLE IF NOT EXISTS `Gifts`(
`Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`PlayerId` INT UNSIGNED NOT NULL,
`GiftPlayerId` INT UNSIGNED NOT NULL,
`ObjectType` VARCHAR(32) NOT NULL,
`ObjectId` VARCHAR(16),
`Currency` VARCHAR(20) NOT NULL,
`Sum` FLOAT(9,2) NOT NULL DEFAULT 0.00,
`Date` INT(11) NOT NULL DEFAULT 0,
`ExpiryDate` INT(11) DEFAULT 0,
`Used` BOOL NOT NULL DEFAULT 0,
PRIMARY KEY (`Id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
